# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name:                gasp
version:             0.1.0.1 # %WASP_VERSION% - annotation for new-release script.
github:              "Lupino/gasp"
license:             MIT
author:              "gasp-lang"
maintainer:          "lmjubuntu@gmail.com"
copyright:           "2020 gasp-lang"

default-extensions:
- OverloadedStrings

extra-source-files:
  - README.md
  - ChangeLog.md

data-dir: data/
data-files:
  - template/**/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Lupino/gasp#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -optP-Wno-nonportable-include-path # To avoid warning caused by .../autogen/cabal_macros.h. on OSX.

library:
  source-dirs: src
  dependencies:
    - filepath
    - parsec
    - mustache
    - text
    - aeson
    - directory
    - bytestring
    - base16-bytestring
    - yaml
    - uuid
    - binary
    - mtl

executables:
  gasp:
    main:                Main.hs
    source-dirs:         cli
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gasp
      - filepath
      - directory
      - mtl
      - fsnotify
      - time
      - text
